# Generated by Django 5.0 on 2024-01-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupuser_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
